### ISSUE TITLE
show emoji

### ISSUE THREAD

**Issue by ibrokemypie** [ibrokemypie/mastalab#13]
currently emoji just show as text

**Comment by ibrokemypie** [comment]
semi-solved
doesnt show animated emoji though
see https://boopsnoot.gq/notes/5c26f723503b28464fb5432f

**Comment by ghost** [comment]
I still have not solved this issue with Mastalab. I need to find a way to use Glide GIF support with spannable string.

**Comment by ibrokemypie** [comment]
does glide suppirt apng? afaik emotes are all pngs

**Comment by ghost** [comment]
Yes, you're right. https://github.com/bumptech/glide/issues/1542

**Comment by ibrokemypie** [comment]
closing in favour of #31 and #32
