### ISSUE TITLE
searching doesnt work

### ISSUE THREAD

**Issue by ibrokemypie** [ibrokemypie/mastalab#21]
should be pretty easy to fix 
https://boopsnoot.gq/docs/en-US/api/endpoints/users/search
https://boopsnoot.gq/docs/en-US/api/endpoints/notes/search
https://boopsnoot.gq/docs/en-US/api/endpoints/hashtags/search

**Comment by ghost** [comment]
Related to #17 
I can change the endpoint for tags and make them use by default `/notes/search_by_tag`

`/hashtags/search` should help for autocompletion of tags
